### ISSUE TITLE
_blog_article partial

### ISSUE THREAD

**Issue by slavakisel** [AlexeyKuznetzov/pdp_junior_ruby_v2#31]
This partial could be renamed to just `_article.html.erb`. After it articles collection rendering could be simplified to:

```ruby
= render blog_articles
```

instead of:

```ruby
= render partial: "articles/blog_article", collection: blog_articles
```

**Comment by AlexeyKuznetzov** [comment]
This is not working because blog articles is collection of `Article` objects and you get this error:
`Missing partial articles/_article`
