### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by slavakisel** [AlexeyKuznetzov/pdp_junior_ruby_v2#32]
- [ ] Feature tests for subscription process
- [ ] Unit tests for interactors
- [ ] Unit tests for react components (see [fs/react-base](https://github.com/fs/react-base) for reference)
- [ ] Tests for home page search (at least on controller level)

**Comment by AlexeyKuznetzov** [comment]
Closed in favor of https://github.com/AlexeyKuznetzov/pdp_senior_ruby/issues/16 @slavakisel
